#!/bin/bash -u

die () {
	echo -e "\e[1;31merror\e[0m: $*" >&2
	exit 1
}

cpucount=$(grep processor /proc/cpuinfo | wc -l)
steamworks_sdk="${STEAMWORKS_SDK:-}"

args=("$@")
declare -A options

declare -A archflags
archflags=(
	[x86_64]="-m64"
	[i686]="-m32 -march=i686"
)

declare -A distflags
distflags=(
	[custom]=""
	[caravel]="-DCARAVELBUILD"
	[steam]="-DCARAVELBUILD -DSTEAMBUILD -I${steamworks_sdk}/public/steam"
)

declare -A distlinkflags
distlinkflags=(
	[custom]=""
	[caravel]=""
	[steam]="-L${steamworks_sdk}/redistributable_bin/linux64 -L${steamworks_sdk}/redistributable_bin/linux32 -lsteam_api"
)

declare -A buildflags
buildflags=(
	[debug]="-Og -D_DEBUG -DENABLE_BREAKPOINTS"
	[debugsan]="-Og -D_DEBUG -DENABLE_BREAKPOINTS -fsanitize=address -fsanitize=undefined"
	[dev]="-Og -D_DEBUG -DENABLE_BREAKPOINTS -DDEV_BUILD"
	[release]="-O2 -DNDEBUG -flto"
	[beta]="-O2 -DNDEBUG -DBETA -flto"
)

declare -A linkflags
linkflags=(
	[debug]=""
	[debugsan]="-fsanitize=address -fsanitize=undefined" #-static-libasan -static-libubsan"
	[dev]=""
	[release]="-flto=${cpucount}"
	[beta]="-flto=${cpucount}"
)

TOPDIR=../..
getoptarg=

options[exec]=
options[cxx]=g++
options[archexec]=
options[arch]=x86_64
options[dist]=custom
options[build]=release
options[nostatic]=false
options[name]=
options[cmake]=false
allargs=

if [[ ${#args[@]} > 0 ]]; then
	allargs="${args[@]}"
	for arg in "${args[@]}"; do
		if [[ ! -z $getoptarg ]]; then
			options[$getoptarg]=$arg
			getoptarg=
		else
			case "$arg" in
				-64)
					options[arch]=x86_64
					options[archexec]=linux64
					;;
				-32)
					options[arch]=i686
					options[archexec]=linux32
					;;
				-exec|-arch|-dist|-build|-cxx)
					getoptarg=${arg/-}
					;;
				-no-static)
					options[${arg//-}]=true
					;;
				-cmake)
					options[cmake]=true
					;;
				-caravel|-custom|-steam)
					options[dist]=${arg/-}
					;;
				-debug|-debugsan|-dev|-release|-beta)
					options[build]=${arg/-}
					;;
				-crossenv)
					options[exec]=crossenv-exec
					;;
				-*)
					die "unknown argument: $arg"
					;;
				*)
					if [[ -z ${options[name]} ]]; then
						options[name]="$arg"
					else
						die "can't set name to \"$arg\" -- it was already set to \"${options[name]}\""
					fi
			esac
		fi
	done
fi
if [[ "${options[dist]}" == "steam" && -z "${steamworks_sdk}" ]]; then
	die "steam build selected, but \$STEAMWORKS_SDK isn't set"
fi
if [[ -z ${options[name]} ]]; then
	NAME=${options[dist]}.${options[build]}.${options[arch]}
else
	NAME=${options[name]}
fi
BUILDDIR=builds/$NAME
EXEC="${options[archexec]} ${options[exec]}"

SDL2_CONFIG="$EXEC static-libs/bin/sdl2-config"
PKG_CONFIG="$EXEC pkg-config"

declare -a libs
libs=(
	${TOPDIR}/DROD
	${TOPDIR}/DRODLib
	${TOPDIR}/CaravelNet
	${TOPDIR}/../FrontEndLib
	${TOPDIR}/../BackEndLib
)

# CMake generation functions
gen_root_cmake () {
	cat <<'CMAKE'
cmake_minimum_required(VERSION 3.16)
project(drodrpg)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Build type configurations
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release)
endif()

# Compiler flags
set(CMAKE_CXX_FLAGS "-pipe -W -Wall -Wno-unused -Wno-unused-parameter -Wno-uninitialized")
set(CMAKE_CXX_FLAGS_DEBUG "-Og -D_DEBUG -DENABLE_BREAKPOINTS -g")
set(CMAKE_CXX_FLAGS_RELEASE "-O2 -DNDEBUG -flto -g")

# Architecture flags
CMAKE
	echo "set(CMAKE_CXX_FLAGS \"\${CMAKE_CXX_FLAGS} ${archflags[${options[arch]}]}\")"
	echo
	cat <<'CMAKE'
# Distribution flags
CMAKE
	echo "add_definitions(${distflags[${options[dist]}]} -DUSE_SDL_MIXER -DDROD_AUTODETECT_REVISION)"
	echo
	cat <<'CMAKE'
# Static libs path
set(STATIC_LIBS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Master/Linux/static-libs")
set(CMAKE_PREFIX_PATH "${STATIC_LIBS_DIR}")

# Include directories
include_directories("${STATIC_LIBS_DIR}/include")

# Library directories
link_directories("${STATIC_LIBS_DIR}/lib")

# Find packages
find_package(PkgConfig REQUIRED)
pkg_check_modules(SDL2 REQUIRED sdl2)

# Add subdirectories
add_subdirectory(../BackEndLib BackEndLib)
add_subdirectory(../FrontEndLib FrontEndLib)
add_subdirectory(../DRODLib DRODLib)
add_subdirectory(../CaravelNet CaravelNet)
add_subdirectory(DROD)
CMAKE
}

gen_lib_cmake () {
	local path="$1"
	local lib=$(basename "$path")
	local vcproj="$path/$lib.2019.vcxproj"
	local files=($(grep 'Include=.*\.cpp' "$vcproj" | sed 's,^.*Include="\(.\\\)\?\([^"]*\)".*$,\2,g' | sort -u))

	cat <<CMAKE
cmake_minimum_required(VERSION 3.16)

# Source files
set(${lib}_SOURCES
CMAKE
	for file in "${files[@]}"; do
		echo "    $file"
	done
	cat <<CMAKE
)

# Create static library
add_library($lib STATIC \${${lib}_SOURCES})

# Include directories
target_include_directories($lib PUBLIC .)
CMAKE

	# Add specific dependencies for libraries
	case "$lib" in
		"FrontEndLib")
			echo "target_link_libraries($lib BackEndLib)"
			;;
		"DRODLib")
			echo "target_link_libraries($lib BackEndLib FrontEndLib)"
			;;
		"CaravelNet")
			echo "target_link_libraries($lib BackEndLib)"
			;;
	esac
}

gen_exe_cmake () {
	local path="$1"
	local lib=$(basename "$path")
	local vcproj="$path/$lib.2019.vcxproj"
	local files=($(grep 'Include=.*\.cpp' "$vcproj" | sed 's,^.*Include="\(.\\\)\?\([^"]*\)".*$,\2,g' | sort -u))

	cat <<CMAKE
cmake_minimum_required(VERSION 3.16)

# Source files
set(DROD_SOURCES
CMAKE
	for file in "${files[@]}"; do
		echo "    $file"
	done
	cat <<CMAKE
)

# Create executable
add_executable(drodrpg \${DROD_SOURCES})

# Link libraries
target_link_libraries(drodrpg
    DRODLib
    CaravelNet
    FrontEndLib
    BackEndLib
    SDL2_mixer SDL2_ttf SDL2 theora vorbisfile vorbis ogg
    jpeg mk4 freetype png16 curl ssl crypto expat jsoncpp
    nghttp2 z pthread m rt dl
)

# Compiler definitions
target_compile_definitions(drodrpg PRIVATE -DUSE_SDL_MIXER)

# Include directories
target_include_directories(drodrpg PRIVATE . ../.. ../../.. ../../../FrontEndLib ../../../BackEndLib)

CMAKE

	# Add steam linking if needed
	if [[ "${options[dist]}" == "steam" ]]; then
		cat <<CMAKE
# Steam library
target_link_directories(drodrpg PRIVATE ${steamworks_sdk}/redistributable_bin/linux64 ${steamworks_sdk}/redistributable_bin/linux32)
target_link_libraries(drodrpg steam_api)
CMAKE
	fi
}

gen_rules () {
	echo "exec = $EXEC"
	echo "arch = ${options[arch]}"
	echo "archflags = ${archflags[${options[arch]}]}"
	echo "distflags = ${distflags[${options[dist]}]}"
	echo "buildflags = ${buildflags[${options[build]}]} -DDROD_AUTODETECT_REVISION"
	echo "linkflags = ${linkflags[${options[build]}]} ${distlinkflags[${options[dist]}]}"
	echo "cxxbin = ${options[cxx]}"
	cat <<'X'

cxx = $exec $cxxbin
ar = $exec gcc-ar
ranlib = $exec gcc-ranlib

config = $distflags -DUSE_SDL_MIXER

optflags = -std=c++11 $archflags $buildflags -g

cflags = $optflags -pipe -W -Wall -Wno-unused -Wno-unused-parameter -Wno-uninitialized
ldflags = $optflags $linkflags -pipe -Wl,-rpath,'$$ORIGIN' -Wl,--as-needed

revision = $$(git rev-parse --short HEAD)
debugsuffix = -${arch}-${revision}.dbg

rule cxx
  depfile = $out.d
  deps = gcc
  command = $cxx -o $out -MMD -MF $out.d $cflags $config $includes -c $in
  description = Compile $out

rule link
  command = $cxx -o $out $ldflags $in $libs && rm -f ${out}-*.dbg && objcopy --only-keep-debug $out ${out}${debugsuffix} && objcopy --add-gnu-debuglink=${out}${debugsuffix} $out && strip --strip-all $out
  description = Link $out

rule ar
  command = $ar cr $out $in && $ranlib $out
  description = Archive $out

rule update-revision
  command = echo "#define DROD_VERSION_REVISION ${revision}" >$out.new && diff -q $out $out.new >/dev/null 2>&1 && rm -f $out.new || mv -f $out.new $out
  description = Update revision
  restat = true

X
	echo "rule regen"
	echo "  command = ./ninjamaker $allargs"
	echo
	echo "builddir = $BUILDDIR"
	local idirs=("-I$BUILDDIR")
	local ilibs=()
	for dir in ${libs[@]}; do
		idirs+=(-I$(dirname $dir))
		ilibs+=($BUILDDIR/$(basename $dir).a)
	done
	cat <<X
includes = ${idirs[@]} -Istatic-libs/include $(${SDL2_CONFIG} --cflags)
staticlibs = -Lstatic-libs/lib -lSDL2_mixer -lSDL2_ttf -lSDL2 -ltheora -lvorbisfile -lvorbis -logg -ljpeg -lmk4 -lfreetype -lpng16 -lcurl -lssl -lcrypto -lexpat -ljsoncpp
dynamiclibs = $(${SDL2_CONFIG} --libs) -lnghttp2 -lz -lpthread -lm -lrt -ldl
build $BUILDDIR/drod: link ${ilibs[@]}
X
	if ${options[nostatic]}; then
		echo "libs = \$staticlibs \$dynamiclibs"
	else
		echo "libs = -static-libgcc -static-libstdc++ -Wl,-Bstatic \$staticlibs -Wl,-Bdynamic \$dynamiclibs"
	fi
}

vcprojs=()
gen_lib_build () {
	local path="$1"
	local lib=$(basename "$path")
	local vcproj="$path/$lib.2019.vcxproj"
	vcprojs+=($vcproj)
	local files=($(grep 'Include=.*\.cpp' "$vcproj" | sed 's,^.*Include="\(.\\\)\?\([^"]*\)".*$,'"$path/\2," | sort -u))
	local objs=()
	for file in ${files[@]}; do
		local obj="$BUILDDIR/$lib/$(basename ${file/.cpp}).o"
		objs+=($obj)
		echo -n "build $obj: cxx $file"
		case "$file" in
			*/GameConstants.cpp)
				echo " | $BUILDDIR/drod-revision.h"
				;;
			*)
				echo
				;;
		esac
	done
	echo "build $BUILDDIR/$lib.a: ar ${objs[@]}"
	echo "build $lib.a: phony $BUILDDIR/$lib.a"
}

if ${options[cmake]}; then
	# CMake mode: generate CMakeLists.txt files
	echo "Generating CMakeLists.txt files..."

	# Generate root CMakeLists.txt in drodrpg directory
	gen_root_cmake >../../CMakeLists.txt
	echo "Generated ../../CMakeLists.txt"

	# Generate CMakeLists.txt for each library
	for lib in "${libs[@]}"; do
		if [[ "$lib" == *"/DROD" ]]; then
			# This is the executable
			gen_exe_cmake "$lib" >"$lib/CMakeLists.txt"
			echo "Generated $lib/CMakeLists.txt (executable)"
		else
			# This is a library
			gen_lib_cmake "$lib" >"$lib/CMakeLists.txt"
			echo "Generated $lib/CMakeLists.txt (library)"
		fi
	done

	echo "CMake files generated successfully!"
	echo "You can now open the drodrpg directory in CLion."
else
	# Original ninja mode
	out=build.$NAME.ninja
	gen_rules >$out
	for lib in "${libs[@]}"; do
		gen_lib_build "$lib" >>$out
	done
	echo "build $BUILDDIR/drod-revision.h: update-revision | always-build" >>$out
	echo "build always-build: phony" >>$out
	echo "build $out: regen ninjamaker ${vcprojs[@]}" >>$out
fi
